// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVDdaHuNdfvhnwvfF6OmXMLReKSBo1ds',
    appId: '1:1012397344271:web:1b0dc14b120fa7cfc0457a',
    messagingSenderId: '1012397344271',
    projectId: 'metaappnew',
    authDomain: 'metaappnew.firebaseapp.com',
    databaseURL: 'https://metaappnew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metaappnew.appspot.com',
    measurementId: 'G-BBHTJJSCJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgMVWT1YtWp25PQ4_x-XCJJF1yt7dermk',
    appId: '1:1012397344271:android:afb5a2126e85ff42c0457a',
    messagingSenderId: '1012397344271',
    projectId: 'metaappnew',
    databaseURL: 'https://metaappnew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metaappnew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANguovCGkRnByX2RmFRzsOmrzmuiaXyS0',
    appId: '1:1012397344271:ios:036c5c42cf88ae98c0457a',
    messagingSenderId: '1012397344271',
    projectId: 'metaappnew',
    databaseURL: 'https://metaappnew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metaappnew.appspot.com',
    iosClientId: '1012397344271-a1hauj1bmipqbqac4bb8hfc518j1ibqi.apps.googleusercontent.com',
    iosBundleId: 'com.metaciti.app',
  );
}
